import * as Color from "colorcrafts";

const shadowSpacing = {
  base: ["0.042rem", "0.055rem", "0.083rem", "0.166rem"],
  lg: ["0.055rem", "0.111rem", "0.166rem", "0.222rem"],
  xl: ["0.111rem", "0.222rem", "0.333rem", "0.444rem"],
};

const textShadow = {
  "light-base": `${shadowSpacing.base[2]} ${shadowSpacing.base[2]} 0 ${Color.Gray["gray-300"]}`,
  "light-lg": `${shadowSpacing.lg[1]} ${shadowSpacing.lg[1]} 0 ${Color.Gray["gray-300"]}`,
  "light-xl": `${shadowSpacing.xl[1]} ${shadowSpacing.xl[1]} 0 ${Color.Gray["gray-300"]}`,
  "bold-base": `-${shadowSpacing.base[1]} -${shadowSpacing.base[1]} 0 ${Color.Gray["gray-800"]},
    ${shadowSpacing.base[1]} -${shadowSpacing.base[1]} 0 ${Color.Gray["gray-800"]},
    -${shadowSpacing.base[1]} ${shadowSpacing.base[1]} 0 ${Color.Gray["gray-800"]},
    ${shadowSpacing.base[1]} ${shadowSpacing.base[1]} 0 ${Color.Gray["gray-800"]},
    -${shadowSpacing.base[0]} -${shadowSpacing.base[1]} 0 ${Color.Gray["gray-800"]},
    ${shadowSpacing.base[0]} -${shadowSpacing.base[1]} 0 ${Color.Gray["gray-800"]},
    -${shadowSpacing.base[0]} ${shadowSpacing.base[1]} 0 ${Color.Gray["gray-800"]},
    ${shadowSpacing.base[0]} ${shadowSpacing.base[1]} 0 ${Color.Gray["gray-800"]},
    -${shadowSpacing.base[1]} -${shadowSpacing.base[0]} 0 ${Color.Gray["gray-800"]},
    ${shadowSpacing.base[1]} -${shadowSpacing.base[0]} 0 ${Color.Gray["gray-800"]},
    -${shadowSpacing.base[1]} ${shadowSpacing.base[0]} 0 ${Color.Gray["gray-800"]},
    ${shadowSpacing.base[1]} ${shadowSpacing.base[0]} 0 ${Color.Gray["gray-800"]},
    ${shadowSpacing.base[0]} ${shadowSpacing.base[3]} 0 ${Color.Gray["gray-800"]},
    ${shadowSpacing.base[1]} ${shadowSpacing.base[3]} 0 ${Color.Gray["gray-800"]},
    ${shadowSpacing.base[2]} ${shadowSpacing.base[3]} 0 ${Color.Gray["gray-800"]},
    ${shadowSpacing.base[3]} ${shadowSpacing.base[3]} 0 ${Color.Gray["gray-800"]},
    ${shadowSpacing.base[3]} ${shadowSpacing.base[2]} 0 ${Color.Gray["gray-800"]},
    ${shadowSpacing.base[3]} ${shadowSpacing.base[1]} 0 ${Color.Gray["gray-800"]},
    ${shadowSpacing.base[3]} ${shadowSpacing.base[0]} 0 ${Color.Gray["gray-800"]}`,
  "bold-lg": `-${shadowSpacing.lg[1]} -${shadowSpacing.lg[1]} 0 ${Color.Gray["gray-800"]},
    ${shadowSpacing.lg[1]} -${shadowSpacing.lg[1]} 0 ${Color.Gray["gray-800"]},
    -${shadowSpacing.lg[1]} ${shadowSpacing.lg[1]} 0 ${Color.Gray["gray-800"]},
    ${shadowSpacing.lg[1]} ${shadowSpacing.lg[1]} 0 ${Color.Gray["gray-800"]},
    -${shadowSpacing.lg[0]} -${shadowSpacing.lg[1]} 0 ${Color.Gray["gray-800"]},
    ${shadowSpacing.lg[0]} -${shadowSpacing.lg[1]} 0 ${Color.Gray["gray-800"]},
    -${shadowSpacing.lg[0]} ${shadowSpacing.lg[1]} 0 ${Color.Gray["gray-800"]},
    ${shadowSpacing.lg[0]} ${shadowSpacing.lg[1]} 0 ${Color.Gray["gray-800"]},
    -${shadowSpacing.lg[1]} -${shadowSpacing.lg[0]} 0 ${Color.Gray["gray-800"]},
    ${shadowSpacing.lg[1]} -${shadowSpacing.lg[0]} 0 ${Color.Gray["gray-800"]},
    -${shadowSpacing.lg[1]} ${shadowSpacing.lg[0]} 0 ${Color.Gray["gray-800"]},
    ${shadowSpacing.lg[1]} ${shadowSpacing.lg[0]} 0 ${Color.Gray["gray-800"]},
    ${shadowSpacing.lg[0]} ${shadowSpacing.lg[3]} 0 ${Color.Gray["gray-800"]},
    ${shadowSpacing.lg[1]} ${shadowSpacing.lg[3]} 0 ${Color.Gray["gray-800"]},
    ${shadowSpacing.lg[2]} ${shadowSpacing.lg[3]} 0 ${Color.Gray["gray-800"]},
    ${shadowSpacing.lg[3]} ${shadowSpacing.lg[3]} 0 ${Color.Gray["gray-800"]},
    ${shadowSpacing.lg[3]} ${shadowSpacing.lg[2]} 0 ${Color.Gray["gray-800"]},
    ${shadowSpacing.lg[3]} ${shadowSpacing.lg[1]} 0 ${Color.Gray["gray-800"]},
    ${shadowSpacing.lg[3]} ${shadowSpacing.lg[0]} 0 ${Color.Gray["gray-800"]}`,
  "bold-xl": `-${shadowSpacing.xl[1]} -${shadowSpacing.xl[1]} 0 ${Color.Gray["gray-800"]},
    ${shadowSpacing.xl[1]} -${shadowSpacing.xl[1]} 0 ${Color.Gray["gray-800"]},
    -${shadowSpacing.xl[1]} ${shadowSpacing.xl[1]} 0 ${Color.Gray["gray-800"]},
    ${shadowSpacing.xl[1]} ${shadowSpacing.xl[1]} 0 ${Color.Gray["gray-800"]},
    -${shadowSpacing.xl[0]} -${shadowSpacing.xl[1]} 0 ${Color.Gray["gray-800"]},
    ${shadowSpacing.xl[0]} -${shadowSpacing.xl[1]} 0 ${Color.Gray["gray-800"]},
    -${shadowSpacing.xl[0]} ${shadowSpacing.xl[1]} 0 ${Color.Gray["gray-800"]},
    ${shadowSpacing.xl[0]} ${shadowSpacing.xl[1]} 0 ${Color.Gray["gray-800"]},
    -${shadowSpacing.xl[1]} -${shadowSpacing.xl[0]} 0 ${Color.Gray["gray-800"]},
    ${shadowSpacing.xl[1]} -${shadowSpacing.xl[0]} 0 ${Color.Gray["gray-800"]},
    -${shadowSpacing.xl[1]} ${shadowSpacing.xl[0]} 0 ${Color.Gray["gray-800"]},
    ${shadowSpacing.xl[1]} ${shadowSpacing.xl[0]} 0 ${Color.Gray["gray-800"]},
    ${shadowSpacing.xl[0]} ${shadowSpacing.xl[3]} 0 ${Color.Gray["gray-800"]},
    ${shadowSpacing.xl[1]} ${shadowSpacing.xl[3]} 0 ${Color.Gray["gray-800"]},
    ${shadowSpacing.xl[2]} ${shadowSpacing.xl[3]} 0 ${Color.Gray["gray-800"]},
    ${shadowSpacing.xl[3]} ${shadowSpacing.xl[3]} 0 ${Color.Gray["gray-800"]},
    ${shadowSpacing.xl[3]} ${shadowSpacing.xl[2]} 0 ${Color.Gray["gray-800"]},
    ${shadowSpacing.xl[3]} ${shadowSpacing.xl[1]} 0 ${Color.Gray["gray-800"]},
    ${shadowSpacing.xl[3]} ${shadowSpacing.xl[0]} 0 ${Color.Gray["gray-800"]}`,
};

export const shadow = { textShadow, shadowSpacing };
