export const POKEMON_TYPE_ICONS: Record<string, string> = {
  normal: "/static/pokemon-type/normal.svg",
  fire: "/static/pokemon-type/fire.svg",
  water: "/static/pokemon-type/water.svg",
  grass: "/static/pokemon-type/grass.svg",
  electric: "/static/pokemon-type/electric.svg",
  ice: "/static/pokemon-type/ice.svg",
  fighting: "/static/pokemon-type/fighting.svg",
  poison: "/static/pokemon-type/poison.svg",
  ground: "/static/pokemon-type/ground.svg",
  flying: "/static/pokemon-type/flying.svg",
  psychic: "/static/pokemon-type/psychic.svg",
  bug: "/static/pokemon-type/bug.svg",
  rock: "/static/pokemon-type/rock.svg",
  ghost: "/static/pokemon-type/ghost.svg",
  dragon: "/static/pokemon-type/dragon.svg",
  dark: "/static/pokemon-type/dark.svg",
  steel: "/static/pokemon-type/steel.svg",
  fairy: "/static/pokemon-type/fairy.svg",
};
