import { VITE_POKEMON_TYPE_ICON } from "@/configs/api";

export const POKEMON_TYPE_ICONS: Record<string, string> = {
  normal: `${VITE_POKEMON_TYPE_ICON}/normal.svg`,
  fire: `${VITE_POKEMON_TYPE_ICON}/fire.svg`,
  water: `${VITE_POKEMON_TYPE_ICON}/water.svg`,
  grass: `${VITE_POKEMON_TYPE_ICON}/grass.svg`,
  electric: `${VITE_POKEMON_TYPE_ICON}/electric.svg`,
  ice: `${VITE_POKEMON_TYPE_ICON}/ice.svg`,
  fighting: `${VITE_POKEMON_TYPE_ICON}/fighting.svg`,
  poison: `${VITE_POKEMON_TYPE_ICON}/poison.svg`,
  ground: `${VITE_POKEMON_TYPE_ICON}/ground.svg`,
  flying: `${VITE_POKEMON_TYPE_ICON}/flying.svg`,
  psychic: `${VITE_POKEMON_TYPE_ICON}/psychic.svg`,
  bug: `${VITE_POKEMON_TYPE_ICON}/bug.svg`,
  rock: `${VITE_POKEMON_TYPE_ICON}/rock.svg`,
  ghost: `${VITE_POKEMON_TYPE_ICON}/ghost.svg`,
  dragon: `${VITE_POKEMON_TYPE_ICON}/dragon.svg`,
  dark: `${VITE_POKEMON_TYPE_ICON}/dark.svg`,
  steel: `${VITE_POKEMON_TYPE_ICON}/steel.svg`,
  fairy: `${VITE_POKEMON_TYPE_ICON}/fairy.svg`,
};

export const TYPE_CHART: Record<string, Record<string, number>> = {
  normal: {
    rock: 0.5,
    ghost: 0,
    steel: 0.5,
  },
  fire: {
    fire: 0.5,
    water: 0.5,
    grass: 2,
    ice: 2,
    bug: 2,
    rock: 0.5,
    dragon: 0.5,
    steel: 2,
  },
  water: {
    fire: 2,
    water: 0.5,
    grass: 0.5,
    ground: 2,
    rock: 2,
    dragon: 0.5,
  },
  electric: {
    water: 2,
    electric: 0.5,
    grass: 0.5,
    ground: 0,
    flying: 2,
    dragon: 0.5,
  },
  grass: {
    fire: 0.5,
    water: 2,
    grass: 0.5,
    poison: 0.5,
    ground: 2,
    flying: 0.5,
    bug: 0.5,
    rock: 2,
    dragon: 0.5,
    steel: 0.5,
  },
  ice: {
    fire: 0.5,
    water: 0.5,
    grass: 2,
    ice: 0.5,
    ground: 2,
    flying: 2,
    dragon: 2,
    steel: 0.5,
  },
  fighting: {
    normal: 2,
    ice: 2,
    poison: 0.5,
    flying: 0.5,
    psychic: 0.5,
    bug: 0.5,
    rock: 2,
    ghost: 0,
    dark: 2,
    steel: 2,
    fairy: 0.5,
  },
  poison: {
    grass: 2,
    poison: 0.5,
    ground: 0.5,
    rock: 0.5,
    ghost: 0.5,
    steel: 0,
    fairy: 2,
  },
  ground: {
    fire: 2,
    electric: 2,
    grass: 0.5,
    poison: 2,
    flying: 0,
    bug: 0.5,
    rock: 2,
    steel: 2,
  },
  flying: {
    electric: 0.5,
    grass: 2,
    fighting: 2,
    bug: 2,
    rock: 0.5,
    steel: 0.5,
  },
  psychic: {
    fighting: 2,
    poison: 2,
    psychic: 0.5,
    dark: 0,
    steel: 0.5,
  },
  bug: {
    fire: 0.5,
    grass: 2,
    fighting: 0.5,
    poison: 0.5,
    flying: 0.5,
    psychic: 2,
    ghost: 0.5,
    dark: 2,
    steel: 0.5,
    fairy: 0.5,
  },
  rock: {
    fire: 2,
    ice: 2,
    fighting: 0.5,
    ground: 0.5,
    flying: 2,
    bug: 2,
    steel: 0.5,
  },
  ghost: {
    normal: 0,
    psychic: 2,
    ghost: 2,
    dark: 0.5,
  },
  dragon: {
    dragon: 2,
    steel: 0.5,
    fairy: 0,
  },
  steel: {
    fire: 0.5,
    water: 0.5,
    electric: 0.5,
    ice: 2,
    rock: 2,
    steel: 0.5,
    fairy: 2,
  },
  dark: {
    fighting: 0.5,
    psychic: 2,
    ghost: 2,
    dark: 0.5,
    fairy: 0.5,
  },
  fairy: {
    fire: 0.5,
    fighting: 2,
    poison: 0.5,
    dragon: 2,
    dark: 2,
    steel: 0.5,
  },
};
