import { colors, shadowSpacing } from ".";

export const textShadow = {
  "light-base": `${shadowSpacing.base[2]} ${shadowSpacing.base[2]} 0 ${colors["gray-400"]}`,
  "light-lg": `${shadowSpacing.lg[1]} ${shadowSpacing.lg[1]} 0 ${colors["gray-400"]}`,
  "light-xl": `${shadowSpacing.xl[1]} ${shadowSpacing.xl[1]} 0 ${colors["gray-400"]}`,
  "bold-base": `-${shadowSpacing.base[1]} -${shadowSpacing.base[1]} 0 ${colors["gray-800"]},
    ${shadowSpacing.base[1]} -${shadowSpacing.base[1]} 0 ${colors["gray-800"]},
    -${shadowSpacing.base[1]} ${shadowSpacing.base[1]} 0 ${colors["gray-800"]},
    ${shadowSpacing.base[1]} ${shadowSpacing.base[1]} 0 ${colors["gray-800"]},
    -${shadowSpacing.base[0]} -${shadowSpacing.base[1]} 0 ${colors["gray-800"]},
    ${shadowSpacing.base[0]} -${shadowSpacing.base[1]} 0 ${colors["gray-800"]},
    -${shadowSpacing.base[0]} ${shadowSpacing.base[1]} 0 ${colors["gray-800"]},
    ${shadowSpacing.base[0]} ${shadowSpacing.base[1]} 0 ${colors["gray-800"]},
    -${shadowSpacing.base[1]} -${shadowSpacing.base[0]} 0 ${colors["gray-800"]},
    ${shadowSpacing.base[1]} -${shadowSpacing.base[0]} 0 ${colors["gray-800"]},
    -${shadowSpacing.base[1]} ${shadowSpacing.base[0]} 0 ${colors["gray-800"]},
    ${shadowSpacing.base[1]} ${shadowSpacing.base[0]} 0 ${colors["gray-800"]},
    ${shadowSpacing.base[0]} ${shadowSpacing.base[3]} 0 ${colors["gray-800"]},
    ${shadowSpacing.base[1]} ${shadowSpacing.base[3]} 0 ${colors["gray-800"]},
    ${shadowSpacing.base[2]} ${shadowSpacing.base[3]} 0 ${colors["gray-800"]},
    ${shadowSpacing.base[3]} ${shadowSpacing.base[3]} 0 ${colors["gray-800"]},
    ${shadowSpacing.base[3]} ${shadowSpacing.base[2]} 0 ${colors["gray-800"]},
    ${shadowSpacing.base[3]} ${shadowSpacing.base[1]} 0 ${colors["gray-800"]},
    ${shadowSpacing.base[3]} ${shadowSpacing.base[0]} 0 ${colors["gray-800"]}`,
  "bold-lg": `-${shadowSpacing.lg[1]} -${shadowSpacing.lg[1]} 0 ${colors["gray-800"]},
    ${shadowSpacing.lg[1]} -${shadowSpacing.lg[1]} 0 ${colors["gray-800"]},
    -${shadowSpacing.lg[1]} ${shadowSpacing.lg[1]} 0 ${colors["gray-800"]},
    ${shadowSpacing.lg[1]} ${shadowSpacing.lg[1]} 0 ${colors["gray-800"]},
    -${shadowSpacing.lg[0]} -${shadowSpacing.lg[1]} 0 ${colors["gray-800"]},
    ${shadowSpacing.lg[0]} -${shadowSpacing.lg[1]} 0 ${colors["gray-800"]},
    -${shadowSpacing.lg[0]} ${shadowSpacing.lg[1]} 0 ${colors["gray-800"]},
    ${shadowSpacing.lg[0]} ${shadowSpacing.lg[1]} 0 ${colors["gray-800"]},
    -${shadowSpacing.lg[1]} -${shadowSpacing.lg[0]} 0 ${colors["gray-800"]},
    ${shadowSpacing.lg[1]} -${shadowSpacing.lg[0]} 0 ${colors["gray-800"]},
    -${shadowSpacing.lg[1]} ${shadowSpacing.lg[0]} 0 ${colors["gray-800"]},
    ${shadowSpacing.lg[1]} ${shadowSpacing.lg[0]} 0 ${colors["gray-800"]},
    ${shadowSpacing.lg[0]} ${shadowSpacing.lg[3]} 0 ${colors["gray-800"]},
    ${shadowSpacing.lg[1]} ${shadowSpacing.lg[3]} 0 ${colors["gray-800"]},
    ${shadowSpacing.lg[2]} ${shadowSpacing.lg[3]} 0 ${colors["gray-800"]},
    ${shadowSpacing.lg[3]} ${shadowSpacing.lg[3]} 0 ${colors["gray-800"]},
    ${shadowSpacing.lg[3]} ${shadowSpacing.lg[2]} 0 ${colors["gray-800"]},
    ${shadowSpacing.lg[3]} ${shadowSpacing.lg[1]} 0 ${colors["gray-800"]},
    ${shadowSpacing.lg[3]} ${shadowSpacing.lg[0]} 0 ${colors["gray-800"]}`,
  "bold-xl": `-${shadowSpacing.xl[1]} -${shadowSpacing.xl[1]} 0 ${colors["gray-800"]},
    ${shadowSpacing.xl[1]} -${shadowSpacing.xl[1]} 0 ${colors["gray-800"]},
    -${shadowSpacing.xl[1]} ${shadowSpacing.xl[1]} 0 ${colors["gray-800"]},
    ${shadowSpacing.xl[1]} ${shadowSpacing.xl[1]} 0 ${colors["gray-800"]},
    -${shadowSpacing.xl[0]} -${shadowSpacing.xl[1]} 0 ${colors["gray-800"]},
    ${shadowSpacing.xl[0]} -${shadowSpacing.xl[1]} 0 ${colors["gray-800"]},
    -${shadowSpacing.xl[0]} ${shadowSpacing.xl[1]} 0 ${colors["gray-800"]},
    ${shadowSpacing.xl[0]} ${shadowSpacing.xl[1]} 0 ${colors["gray-800"]},
    -${shadowSpacing.xl[1]} -${shadowSpacing.xl[0]} 0 ${colors["gray-800"]},
    ${shadowSpacing.xl[1]} -${shadowSpacing.xl[0]} 0 ${colors["gray-800"]},
    -${shadowSpacing.xl[1]} ${shadowSpacing.xl[0]} 0 ${colors["gray-800"]},
    ${shadowSpacing.xl[1]} ${shadowSpacing.xl[0]} 0 ${colors["gray-800"]},
    ${shadowSpacing.xl[0]} ${shadowSpacing.xl[3]} 0 ${colors["gray-800"]},
    ${shadowSpacing.xl[1]} ${shadowSpacing.xl[3]} 0 ${colors["gray-800"]},
    ${shadowSpacing.xl[2]} ${shadowSpacing.xl[3]} 0 ${colors["gray-800"]},
    ${shadowSpacing.xl[3]} ${shadowSpacing.xl[3]} 0 ${colors["gray-800"]},
    ${shadowSpacing.xl[3]} ${shadowSpacing.xl[2]} 0 ${colors["gray-800"]},
    ${shadowSpacing.xl[3]} ${shadowSpacing.xl[1]} 0 ${colors["gray-800"]},
    ${shadowSpacing.xl[3]} ${shadowSpacing.xl[0]} 0 ${colors["gray-800"]}`,
};
