/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as MyPokemonRouteImport } from "./routes/my-pokemon";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as PokemonsIndexRouteImport } from "./routes/pokemons.index";
import { Route as PokemonsPokemonNameRouteImport } from "./routes/pokemons.$pokemonName";

const MyPokemonRoute = MyPokemonRouteImport.update({
  id: "/my-pokemon",
  path: "/my-pokemon",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const PokemonsIndexRoute = PokemonsIndexRouteImport.update({
  id: "/pokemons/",
  path: "/pokemons/",
  getParentRoute: () => rootRouteImport,
} as any);
const PokemonsPokemonNameRoute = PokemonsPokemonNameRouteImport.update({
  id: "/pokemons/$pokemonName",
  path: "/pokemons/$pokemonName",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/my-pokemon": typeof MyPokemonRoute;
  "/pokemons/$pokemonName": typeof PokemonsPokemonNameRoute;
  "/pokemons": typeof PokemonsIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/my-pokemon": typeof MyPokemonRoute;
  "/pokemons/$pokemonName": typeof PokemonsPokemonNameRoute;
  "/pokemons": typeof PokemonsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/my-pokemon": typeof MyPokemonRoute;
  "/pokemons/$pokemonName": typeof PokemonsPokemonNameRoute;
  "/pokemons/": typeof PokemonsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/my-pokemon" | "/pokemons/$pokemonName" | "/pokemons";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/my-pokemon" | "/pokemons/$pokemonName" | "/pokemons";
  id:
    | "__root__"
    | "/"
    | "/my-pokemon"
    | "/pokemons/$pokemonName"
    | "/pokemons/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  MyPokemonRoute: typeof MyPokemonRoute;
  PokemonsPokemonNameRoute: typeof PokemonsPokemonNameRoute;
  PokemonsIndexRoute: typeof PokemonsIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/my-pokemon": {
      id: "/my-pokemon";
      path: "/my-pokemon";
      fullPath: "/my-pokemon";
      preLoaderRoute: typeof MyPokemonRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/pokemons/": {
      id: "/pokemons/";
      path: "/pokemons";
      fullPath: "/pokemons";
      preLoaderRoute: typeof PokemonsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/pokemons/$pokemonName": {
      id: "/pokemons/$pokemonName";
      path: "/pokemons/$pokemonName";
      fullPath: "/pokemons/$pokemonName";
      preLoaderRoute: typeof PokemonsPokemonNameRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MyPokemonRoute: MyPokemonRoute,
  PokemonsPokemonNameRoute: PokemonsPokemonNameRoute,
  PokemonsIndexRoute: PokemonsIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
